[versions]
agp = "8.11.2"
appcompat = "1.7.1"
compose = "1.9.3"
kotlin = "2.2.21-titan-208"
kotlinx-coroutines = "1.10.2"
stripe-android = "22.1.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
stripe-android = { module = "com.stripe:stripe-android", version.ref = "stripe-android" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
spmForKmp = { id = "io.github.frankois944.spmForKmp", version = "1.0.4" }